apiVersion: apps/v1
kind: Deployment
metadata:
  name: akscosmosdemo-deployment
  labels:
    app: akscosmosdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akscosmosdemo
  template:
    metadata:
      labels:
        app: akscosmosdemo
    spec:
      containers:
      - name: akscosmosdemo
        image: docker.io/tushpatt/demo:akscosmosdemoimage
        ports:
        - containerPort: 9860
---
apiVersion: v1
kind: Service
metadata:
  name: akscosmosdemo
spec:
  type: LoadBalancer
  ports:
  - port: 9860
  selector:
    app: akscosmosdemo